[project]
name = "lian"
version = "0.1.0"
description = "LIAN Algorithm"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "notebook>=7.5.0",
    "numpy>=2.3.5",
    "opencv-python>=4.11.0.86",
]
